const getters = {
    userInfo:state => state.user.userInfo,
    sidebar: state => state.app.sidebar,
    size: state => state.app.size,
    device: state => state.app.device,
    visitedViews: state => state.tagsView.visitedViews,
    cachedViews: state => state.tagsView.cachedViews,
    token: state => state.user.token,
    avatar: state => state.user.avatar,
    name: state => state.user.name,
    introduction: state => state.user.introduction,
    roles: state => state.user.roles,
    permission_routes: state => state.permission.routes,
    errorLogs: state => state.errorLog.logs,
    enterpriseApp:state => state.MineApp.enterpriseApp,
    hasApp:state => state.MineApp.hasApp,
    adminApp:state => state.MineApp.adminApp,
    shortcutList:state => state.MineApp.shortcutList,
    userId:state => state.user.userId,
    orgId:state => state.user.orgId,
}
export default getters
